### ISSUE TITLE
About the dataset and training code for scenes in Rising Sea-level Simulation section.

### ISSUE THREAD

**Issue by BPAWD** [y-u-a-n-l-i/Climate_NeRF#1]
Congrats to the excellent work! I'm very interested in the large-scale scene examples shown in the project page's Rising Sea-level Simulation section. Could you release the dataset and training code for this part? That will be very helpful for comparison. Thanks.

**Comment by y-u-a-n-l-i** [comment]
Hi, thanks for your attention to our project. I'm also sorry for the late response. We are checking the license issue of that dataset downloaded from Adobe stock to make sure we can distribute it.

**Comment by BPAWD** [comment]
Looking forward to the release!

**Comment by zhihao-lin** [comment]
Thanks for your interest in our project, and we download the assets from Adobe Stock

The license information is listed as fallowing:

Enhanced licenses are available for Adobe Stock videos, templates, 3D assets, and Premium Collection.
With an Enhanced license, you may:
- Use the asset with all the rights granted in the Standard license.
- Reproduce the asset beyond the 500,000 copy/viewer restriction.

With an Enhanced license, you **may not**:
- **Distribute the stand-alone file.**
- Create merchandise, templates, or other products for resale or distribution where the primary value of the product is associated with the asset itself. For example, you can’t use the asset to create a poster, t-shirt, or coffee mug that someone would buy specifically because of the asset printed on it.

As a result, we are sorry that the processed data may not be released.
However, we are happy to reveal the process:

1. find the proper assets on Adobe stock (take Eiffel tower for example, you could find [here]( https://stock.adobe.com/search/video?filters%5Bcontent_type%3Aphoto%5D=0&filters%5Bcontent_type%3Aillustration%5D=0&filters%5Bcontent_type%3Azip_vector%5D=0&filters%5Bcontent_type%3Avideo%5D=1&filters%5Bcontent_type%3Atemplate%5D=0&filters%5Bcontent_type%3A3d%5D=0&filters%5Bcontent_type%3Aaudio%5D=0&filters%5Binclude_stock_enterprise%5D=1&filters%5Bis_editorial%5D=0&filters%5Bfree_collection%5D=0&filters%5Bcontent_type%3Aimage%5D=0&k=Eiffel+Tower+&order=relevance&safe_search=1&limit=100&search_page=1&search_type=usertyped&acp=&aco=Eiffel+Tower+&get_facets=0))
2. Estimate camera poses with NeRFstudio pipeline for [custom data](https://docs.nerf.studio/quickstart/custom_dataset.html).
3. Load the data with [colmap_adobe.py](https://github.com/y-u-a-n-l-i/Climate_NeRF/blob/main/datasets/colmap_adobe.py) and perform reconstruction
4. Gravity orientation estimation for rising sea-level simulation: run PCA on sparse point cloud from colmap and choose the basis with smallest eigenvalue.

Hope this helps!

**Comment by chih-hao-lin** [comment]
please feel free to reopen if further discussion is needed
