### ISSUE TITLE
About the coordinate system using during rendering.

### ISSUE THREAD

**Issue by Lynchrocket** [y-u-a-n-l-i/Climate_NeRF#16]
Congrats to your great work! 
I am learning from this project and there is something I cannot understand. Is the ray sampled from the NDC space or directly from the world coordinate space?  According to `get_rays()` function in `ray_utils.py`, it seems that the rays are not transformed into NDC space . If it is always the world coordinate space, what is the unit of the `rays_t`? Or its meaning. (which approximately ranges from 0.0 to 13.0 using kitti360 dataset)
Thanks for your reply.

**Comment by y-u-a-n-l-i** [comment]
All rays are sampled in the world coordinate space, following [ngp_pl](https://github.com/kwea123/ngp_pl). I think by `rays_t` you mean something like `results['ts']` in the rendering code. It means the distances of samples along rays.

**Comment by Lynchrocket** [comment]
Thank you for your reply. Apologize for my late appreciation because of QingMing Festival and middle defense for dissertation.
I found that the depth is estimated by `dt`, which is calculated by `calc_dt()` in `raymarching.cu`. I am trying transforming the depth into point cloud so I am wondering what is the unit of the depth. Is it metre or just a relative value without definite unit?

**Comment by y-u-a-n-l-i** [comment]
Hi,




The unit of the depth has no meaning.




Best,

Yuan







-----原始邮件-----
发件人:Lynchrocket ***@***.***>
发送时间:2024-04-25 15:34:22 (星期四)
收件人: y-u-a-n-l-i/Climate_NeRF ***@***.***>
抄送: "Yuan Li" ***@***.***>, Comment ***@***.***>
主题: Re: [y-u-a-n-l-i/Climate_NeRF] About the coordinate system using during rendering. (Issue #16)






Thank you for your reply. Apologize for my late appreciation because of QingMing Festival and middle defense for dissertation.
I found that the depth is estimated by dt, which is calculated by calc_dt() in raymarching.cu. I am trying transforming the depth into point cloud so I am wondering what is the unit of the depth. Is it metre or just a relative value without definite unit?

**Comment by Lynchrocket** [comment]
I got it. Thank you very much.

**Comment by tendo518** [comment]
@y-u-a-n-l-i Thank you for sharing the code! I have a similar question. I am wondering if there is a way to translate `t` into actual depth measurements in meter? It seems that other NeRF implementations are capable of doing so (such as NeRFStudio), but the implementation of ClimateNeRF seems different...

**Comment by y-u-a-n-l-i** [comment]
For those scenes reconstructed using Colmap poses, units of depth and poses are meaningless. You can refer to this [issue](https://github.com/nerfstudio-project/nerfstudio/issues/1247#issuecomment-1400890145) in Nerfstudio's repo. If you have ground truth depth maps in real-world coordinates (like meter in unit), you might calculate a scale transition by performing least square between rendered depth maps and g.t. depth maps.
